export const communities = [
    {
        id: 0,
        name: "GDSC Galgotia",
        image: "/community/gdscgalgotia.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 1,
        name: "GFG Galgotia",
        image: "/community/gfggalgotia.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 2,
        name: "LOOP Galgotia",
        image: "/community/loopgalgotia.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 3,
        name: "GFG NIET",
        image: "/community/nietgfg.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 4,
        name: "GDSC Jaypee",
        image: "/community/gdscjiit.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 5,
        name: "ForgeNest",
        image: "/community/forgenest.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 6,
        name: "Code Geeks",
        image: "/community/codegeeks.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 7,
        name: "Anveshan BPIT",
        image: "/community/anveshan.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 8,
        name: "D4",
        image: "/community/d4.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 9,
        name: "InternFreak",
        image: "/community/internfreak.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 10,
        name: "Byte Brigades",
        image: "/community/byte.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 11,
        name: "Namespace BPIT",
        image: "/community/namespace.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 12,
        name: "15 Fourteen",
        image: "/community/fifteen.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
    {
        id: 13,
        name: "FreSources",
        image: "/community/fresources.webp",
        // linkedin: "https://www.linkedin.com/in/sushilkumar93?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        // github: "",
        // twitter: "",
    },
]
