export const mentors = [
    {
        id: 0,
        name: "Simarpreet Singh",
        image: "/mentors/simarpreet.webp",
        linkedin: "https://www.linkedin.com/in/programmersingh/",
        github: "",
        twitter: "",
    },
    {
        id: 1,
        name: "Vansh Kapoor",
        image: "/mentors/vansh-kapoor.webp",
        linkedin: "https://www.linkedin.com/in/vansh-kapoor/",
        github: "",
        twitter: "",
    },
    {
        id: 2,
        name: "Ashwani Kumar",
        image: "/mentors/ashwini-sir.webp",
        linkedin: "https://www.linkedin.com/in/akumar07",
        github: "",
        twitter: "",
    },
    {
        id: 3,
        name: "Udayveer Singh",
        image: "/mentors/udayveer-singh.webp",
        linkedin: "https://www.linkedin.com/in/udayveer-singh/",
        github: "",
        twitter: "",
    },
   
    {
        id: 4,
        name: "Amanpreet Kaur",
        image: "/mentors/Amanpreet-Kaur.webp",
        linkedin: "https://www.linkedin.com/in/kauramanp/",
        github: "",
        twitter: "",
    },
    {
        id: 5,
        name: "Dhruv Mehta",
        image: "/mentors/Dhruv-Mehta.webp",
        linkedin: "https://www.linkedin.com/in/dhruv-mehta-194dev/",
        github: "",
        twitter: "",
    },
    {
        id: 6,
        name: "Shubhang Mathur",
        image: "/mentors/Shubhang Mathur.webp",
        linkedin: "https://www.linkedin.com/in/shubhang-mathur-953489212/",
        github: "",
        twitter: "",
    },
    {
        id: 7,
        name: "Jatin Kumar",
        image: "/mentors/Jatin.webp",
        linkedin: "https://www.linkedin.com/in/shubhang-mathur-953489212/",
        github: "",
        twitter: "",
    },
]
