export const team = [
    {
        id: 0,
        name: "Pushpak Kumawat",
        image: "/team/pushpak.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 1,
        name: "Srishti Srivastava",
        image: "/team/srishti.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 2,
        name: "Tanmay Newatia",
        image: "/team/tanmay.webp",
        linkedin: "https://www.linkedin.com/in/tanmaynewatia/",
        github: "https://www.github.com/TanmayNewatia",
        twitter: "https://twitter.com/Tanmay_Newatia",
    },
    {
        id: 3,
        name: "Arshdeep Singh ",
        image: "/team/arshdeep.webp",
        linkedin: "https://www.linkedin.com/in/arshdeep-singh-virdi-a72a3a259/",
        github: "",
        twitter: "",
    },
    {
        id: 4,
        name: "Harsh Dhiman",
        image: "/team/Harsh-Dhiman.webp",
        linkedin: "https://www.linkedin.com/in/harsh-dhiman-2a111422b/",
        github: "https://github.com/harshdhiman03",
        twitter: "",
    },
    {
        id: 5,
        name: "Aditya Suman",
        image: "/team/aditya-suman.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 6,
        name: "Adarsh Rai",
        image: "/team/adarsh.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 7,
        name: "Manvi Agrawal",
        image: "/team/manvi.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 8,
        name: "Shobhit Singh",
        image: "/team/shobhit.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 9,
        name: "Vartika Bajpai",
        image: "/team/vartika.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 10,
        name: "Saksham Tyagi",
        image: "/team/saksham.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 11,
        name: "Prajjwal Tyagi",
        image: "/team/prajjwal.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 12,
        name: "Nikhil Bhati",
        image: "/team/nikhil.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 13,
        name: "Shivam Singh",
        image: "/team/shivam.webp",
        linkedin: "",
        github: "",
        twitter: "",
    }
]