export const volunteer = [
    {
        id: 0,
        name: "Zara",
        image: "/team/volunteer/Zara.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 1,
        name: " Pavani",
        image: "/team/volunteer/Pavani.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 2,
        name: " Tanuj Kochar",
        image: "/team/volunteer/Tanuj.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 3,
        name: "Sakshi Khurana",
        image: "/team/volunteer/Sakshi.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 4,
        name: "Sowmya Garg",
        image: "/team/volunteer/Sowmya.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 5,
        name: "Debasmita Mukherjee",
        image: "/team/volunteer/DebasmitaMukherjee.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 6,
        name: "Aastha Vats",
        image: "/team/aastha.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 7,
        name: "Anurag Parashar",
        image: "/team/anurag.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 8,
        name: "Ishita Singhal",
        image: "/team/volunteer/Ishita.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 9,
        name: "Anshita Mishra",
        image: "/team/volunteer/Anshita.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 10,
        name: "Parinita Singh",
        image: "/team/volunteer/Parinita.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 11,
        name: "Shreshth",
        image: "/team/volunteer/Shreshth.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 12,
        name: "Soumya",
        image: "/team/volunteer/Soumya.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 13,
        name: "Harshit Verma",
        image: "/team/volunteer/harshitverma.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 14,
        name: "Archit Saxena",
        image: "/team/volunteer/architsaxena.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 15,
        name: "Arpit Singhal",
        image: "/team/volunteer/arpitsinghal.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 16,
        name: "Pankhuri Gupta",
        image: "/team/volunteer/Pankhuri.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 17,
        name: "Rishi Rishabh",
        image: "/team/volunteer/Rishi.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 18,
        name: "Swarnim Burnwal",
        image: "/team/volunteer/swarnim.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {

        id:19,
        name:"Rishi Rishabh",
        image:"/team/volunteer/Rishi.webp", 
      linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id:20,
        name:"Ayush Gupta",
        image:"/team/volunteer/Ayush.webp", 
      linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id:21,
        name:"Ajeet Singh Rawat",
        image:"/team/volunteer/Ajeet.webp", 
      linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id:22,
        name:"Mukul bhalla",
        image:"/team/volunteer/Mukul.webp", 
      linkedin: "",

        github: "",

        twitter: "",
    },
    
{
        id: 23,
        name: "Md. Aftab Alam",
        image: "/team/volunteer/aftabalam.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 24,
        name: "Shashwat Singh",
        image: "/team/volunteer/shashwatsingh.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 25,
        name: "Saksham Dwivedi",
        image: "/team/volunteer/saksham.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 26,
        name: "Manav Singh Shekhawat",
        image: "/team/volunteer/manav.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 27,
        name: "Sanya Vohra",
        image: "/team/volunteer/Sanya.webp",
        linkedin: "",
        github: "",
        twitter: "",
    },
    {
        id: 28,
        name: "Mradul Kapoor",
        image: "/team/volunteer/Mradul.webp",
        linkedin: "",
        github: "",
        twitter: "",
    }


]